### ISSUE TITLE
I do not understand

### ISSUE THREAD

**Issue by enri90** [gitex-flow/gitex-flow-vscode#12]
Failed to merge release branch. Error: Command failed: git flow release finish -m 1.0.0 "1.0.0"
git@github.com: Permission denied (publickey).
fatal: Unable to read from the remote repository.
Fatal: Could not fetch release/1.0.0 from origin.

hello I followed the procedure at the time of closing the release tells me that I don't have the permits
The project is private on Github

With vscode work Commit and Push

**Comment by jrebmann** [comment]
Hi @enri90, thanks for your question.

Unfortunately I need a little more information about what you have executed and what exactly happened. Maybe a screenshot could be helpful.

The only thing I see is that you tried to finish a release branch. So I assume the creation of a release was successful?

And what vscode git commands working for you?

**Comment by jrebmann** [comment]
I am closing this topic due to inactivity. Please reopen it if the problem persists.
