### ISSUE TITLE
How to merge develop into release in VSCode?

### ISSUE THREAD

**Issue by 3344567** [gitex-flow/gitex-flow-vscode#6]
According to the git-flow tips,
step1,click Feature finish ,merge feature into develop，
step2,Where should I click,merge develop into release ？
step3, click Release finish, merge release into master
Is my understanding wrong?

**Comment by CuddlySheep** [comment]
The idea of a release in git-flow is that the code is frozen on develop at the time of the release. I.e. from the time of the freeze there is a feature stop and only bugfixes are checked in on the release branch.

A release branch is therefore used to stabilize and consolidate the code. When the code is tested sufficiently, it can be released productively and the release can be finished.

Your question about how develop can be merged into release is thus not provided for in git-flow. The idea would be to either close the open release and create a new one (then with the new features) or delete the open release branch and start a release again.

I hope this answer is helpful for you.

**Comment by 3344567** [comment]
Thanks, You're right
