### ISSUE TITLE
Fatal: Not a git repository

### ISSUE THREAD

**Issue by inaryart** [gitex-flow/gitex-flow-vscode#7]
```
Failed to create hotfix branch. Error: Command failed: cd "e:\job_src\test" && git flow config
Fatal: Not a git repository
```
i'm sure **test** is git repository

**Comment by CuddlySheep** [comment]
Thank you for your report.
I was able to reproduce the error with a colleague and figured out that the error occurs on Windows systems when the git repository is not on the primary partition.
